// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cliente_Proto.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_Cliente_5fProto_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Cliente_5fProto_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Cliente_5fProto_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Cliente_5fProto_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Cliente_5fProto_2eproto;
namespace Cliente_Productor {
class Mensaje;
struct MensajeDefaultTypeInternal;
extern MensajeDefaultTypeInternal _Mensaje_default_instance_;
class Vacio;
struct VacioDefaultTypeInternal;
extern VacioDefaultTypeInternal _Vacio_default_instance_;
class estadoMSJ;
struct estadoMSJDefaultTypeInternal;
extern estadoMSJDefaultTypeInternal _estadoMSJ_default_instance_;
class solicitudMSJ;
struct solicitudMSJDefaultTypeInternal;
extern solicitudMSJDefaultTypeInternal _solicitudMSJ_default_instance_;
}  // namespace Cliente_Productor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Cliente_Productor {

// ===================================================================


// -------------------------------------------------------------------

class solicitudMSJ final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Cliente_Productor.solicitudMSJ) */ {
 public:
  inline solicitudMSJ() : solicitudMSJ(nullptr) {}
  ~solicitudMSJ() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR solicitudMSJ(
      ::google::protobuf::internal::ConstantInitialized);

  inline solicitudMSJ(const solicitudMSJ& from) : solicitudMSJ(nullptr, from) {}
  inline solicitudMSJ(solicitudMSJ&& from) noexcept
      : solicitudMSJ(nullptr, std::move(from)) {}
  inline solicitudMSJ& operator=(const solicitudMSJ& from) {
    CopyFrom(from);
    return *this;
  }
  inline solicitudMSJ& operator=(solicitudMSJ&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const solicitudMSJ& default_instance() {
    return *internal_default_instance();
  }
  static inline const solicitudMSJ* internal_default_instance() {
    return reinterpret_cast<const solicitudMSJ*>(
        &_solicitudMSJ_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(solicitudMSJ& a, solicitudMSJ& b) { a.Swap(&b); }
  inline void Swap(solicitudMSJ* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(solicitudMSJ* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  solicitudMSJ* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<solicitudMSJ>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const solicitudMSJ& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const solicitudMSJ& from) { solicitudMSJ::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(solicitudMSJ* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Cliente_Productor.solicitudMSJ"; }

 protected:
  explicit solicitudMSJ(::google::protobuf::Arena* arena);
  solicitudMSJ(::google::protobuf::Arena* arena, const solicitudMSJ& from);
  solicitudMSJ(::google::protobuf::Arena* arena, solicitudMSJ&& from) noexcept
      : solicitudMSJ(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTemaFieldNumber = 1,
    kIdMensajeFieldNumber = 2,
  };
  // int32 tema = 1;
  void clear_tema() ;
  ::int32_t tema() const;
  void set_tema(::int32_t value);

  private:
  ::int32_t _internal_tema() const;
  void _internal_set_tema(::int32_t value);

  public:
  // int32 idMensaje = 2;
  void clear_idmensaje() ;
  ::int32_t idmensaje() const;
  void set_idmensaje(::int32_t value);

  private:
  ::int32_t _internal_idmensaje() const;
  void _internal_set_idmensaje(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Cliente_Productor.solicitudMSJ)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::int32_t tema_;
    ::int32_t idmensaje_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Cliente_5fProto_2eproto;
};
// -------------------------------------------------------------------

class estadoMSJ final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Cliente_Productor.estadoMSJ) */ {
 public:
  inline estadoMSJ() : estadoMSJ(nullptr) {}
  ~estadoMSJ() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR estadoMSJ(
      ::google::protobuf::internal::ConstantInitialized);

  inline estadoMSJ(const estadoMSJ& from) : estadoMSJ(nullptr, from) {}
  inline estadoMSJ(estadoMSJ&& from) noexcept
      : estadoMSJ(nullptr, std::move(from)) {}
  inline estadoMSJ& operator=(const estadoMSJ& from) {
    CopyFrom(from);
    return *this;
  }
  inline estadoMSJ& operator=(estadoMSJ&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const estadoMSJ& default_instance() {
    return *internal_default_instance();
  }
  static inline const estadoMSJ* internal_default_instance() {
    return reinterpret_cast<const estadoMSJ*>(
        &_estadoMSJ_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(estadoMSJ& a, estadoMSJ& b) { a.Swap(&b); }
  inline void Swap(estadoMSJ* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(estadoMSJ* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  estadoMSJ* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<estadoMSJ>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const estadoMSJ& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const estadoMSJ& from) { estadoMSJ::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(estadoMSJ* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Cliente_Productor.estadoMSJ"; }

 protected:
  explicit estadoMSJ(::google::protobuf::Arena* arena);
  estadoMSJ(::google::protobuf::Arena* arena, const estadoMSJ& from);
  estadoMSJ(::google::protobuf::Arena* arena, estadoMSJ&& from) noexcept
      : estadoMSJ(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRecibidoFieldNumber = 1,
  };
  // bool recibido = 1;
  void clear_recibido() ;
  bool recibido() const;
  void set_recibido(bool value);

  private:
  bool _internal_recibido() const;
  void _internal_set_recibido(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Cliente_Productor.estadoMSJ)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    bool recibido_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Cliente_5fProto_2eproto;
};
// -------------------------------------------------------------------

class Vacio final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Cliente_Productor.Vacio) */ {
 public:
  inline Vacio() : Vacio(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Vacio(
      ::google::protobuf::internal::ConstantInitialized);

  inline Vacio(const Vacio& from) : Vacio(nullptr, from) {}
  inline Vacio(Vacio&& from) noexcept
      : Vacio(nullptr, std::move(from)) {}
  inline Vacio& operator=(const Vacio& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vacio& operator=(Vacio&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vacio& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vacio* internal_default_instance() {
    return reinterpret_cast<const Vacio*>(
        &_Vacio_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Vacio& a, Vacio& b) { a.Swap(&b); }
  inline void Swap(Vacio* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vacio* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vacio* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<Vacio>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Vacio& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Vacio& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Cliente_Productor.Vacio"; }

 protected:
  explicit Vacio(::google::protobuf::Arena* arena);
  Vacio(::google::protobuf::Arena* arena, const Vacio& from);
  Vacio(::google::protobuf::Arena* arena, Vacio&& from) noexcept
      : Vacio(arena) {
    *this = ::std::move(from);
  }

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Cliente_Productor.Vacio)
 private:
  class _Internal;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_Cliente_5fProto_2eproto;
};
// -------------------------------------------------------------------

class Mensaje final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Cliente_Productor.Mensaje) */ {
 public:
  inline Mensaje() : Mensaje(nullptr) {}
  ~Mensaje() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Mensaje(
      ::google::protobuf::internal::ConstantInitialized);

  inline Mensaje(const Mensaje& from) : Mensaje(nullptr, from) {}
  inline Mensaje(Mensaje&& from) noexcept
      : Mensaje(nullptr, std::move(from)) {}
  inline Mensaje& operator=(const Mensaje& from) {
    CopyFrom(from);
    return *this;
  }
  inline Mensaje& operator=(Mensaje&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Mensaje& default_instance() {
    return *internal_default_instance();
  }
  static inline const Mensaje* internal_default_instance() {
    return reinterpret_cast<const Mensaje*>(
        &_Mensaje_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Mensaje& a, Mensaje& b) { a.Swap(&b); }
  inline void Swap(Mensaje* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Mensaje* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Mensaje* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Mensaje>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Mensaje& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Mensaje& from) { Mensaje::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Mensaje* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Cliente_Productor.Mensaje"; }

 protected:
  explicit Mensaje(::google::protobuf::Arena* arena);
  Mensaje(::google::protobuf::Arena* arena, const Mensaje& from);
  Mensaje(::google::protobuf::Arena* arena, Mensaje&& from) noexcept
      : Mensaje(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kContenidoFieldNumber = 3,
    kTemaFieldNumber = 1,
    kIdMensajeFieldNumber = 2,
  };
  // string contenido = 3;
  void clear_contenido() ;
  const std::string& contenido() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_contenido(Arg_&& arg, Args_... args);
  std::string* mutable_contenido();
  PROTOBUF_NODISCARD std::string* release_contenido();
  void set_allocated_contenido(std::string* value);

  private:
  const std::string& _internal_contenido() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_contenido(
      const std::string& value);
  std::string* _internal_mutable_contenido();

  public:
  // int32 tema = 1;
  void clear_tema() ;
  ::int32_t tema() const;
  void set_tema(::int32_t value);

  private:
  ::int32_t _internal_tema() const;
  void _internal_set_tema(::int32_t value);

  public:
  // int32 idMensaje = 2;
  void clear_idmensaje() ;
  ::int32_t idmensaje() const;
  void set_idmensaje(::int32_t value);

  private:
  ::int32_t _internal_idmensaje() const;
  void _internal_set_idmensaje(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Cliente_Productor.Mensaje)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      43, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr contenido_;
    ::int32_t tema_;
    ::int32_t idmensaje_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Cliente_5fProto_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Mensaje

// int32 tema = 1;
inline void Mensaje::clear_tema() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tema_ = 0;
}
inline ::int32_t Mensaje::tema() const {
  // @@protoc_insertion_point(field_get:Cliente_Productor.Mensaje.tema)
  return _internal_tema();
}
inline void Mensaje::set_tema(::int32_t value) {
  _internal_set_tema(value);
  // @@protoc_insertion_point(field_set:Cliente_Productor.Mensaje.tema)
}
inline ::int32_t Mensaje::_internal_tema() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tema_;
}
inline void Mensaje::_internal_set_tema(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tema_ = value;
}

// int32 idMensaje = 2;
inline void Mensaje::clear_idmensaje() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.idmensaje_ = 0;
}
inline ::int32_t Mensaje::idmensaje() const {
  // @@protoc_insertion_point(field_get:Cliente_Productor.Mensaje.idMensaje)
  return _internal_idmensaje();
}
inline void Mensaje::set_idmensaje(::int32_t value) {
  _internal_set_idmensaje(value);
  // @@protoc_insertion_point(field_set:Cliente_Productor.Mensaje.idMensaje)
}
inline ::int32_t Mensaje::_internal_idmensaje() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.idmensaje_;
}
inline void Mensaje::_internal_set_idmensaje(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.idmensaje_ = value;
}

// string contenido = 3;
inline void Mensaje::clear_contenido() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.contenido_.ClearToEmpty();
}
inline const std::string& Mensaje::contenido() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Cliente_Productor.Mensaje.contenido)
  return _internal_contenido();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Mensaje::set_contenido(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.contenido_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Cliente_Productor.Mensaje.contenido)
}
inline std::string* Mensaje::mutable_contenido() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_contenido();
  // @@protoc_insertion_point(field_mutable:Cliente_Productor.Mensaje.contenido)
  return _s;
}
inline const std::string& Mensaje::_internal_contenido() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.contenido_.Get();
}
inline void Mensaje::_internal_set_contenido(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.contenido_.Set(value, GetArena());
}
inline std::string* Mensaje::_internal_mutable_contenido() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.contenido_.Mutable( GetArena());
}
inline std::string* Mensaje::release_contenido() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Cliente_Productor.Mensaje.contenido)
  return _impl_.contenido_.Release();
}
inline void Mensaje::set_allocated_contenido(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.contenido_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.contenido_.IsDefault()) {
          _impl_.contenido_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Cliente_Productor.Mensaje.contenido)
}

// -------------------------------------------------------------------

// estadoMSJ

// bool recibido = 1;
inline void estadoMSJ::clear_recibido() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.recibido_ = false;
}
inline bool estadoMSJ::recibido() const {
  // @@protoc_insertion_point(field_get:Cliente_Productor.estadoMSJ.recibido)
  return _internal_recibido();
}
inline void estadoMSJ::set_recibido(bool value) {
  _internal_set_recibido(value);
  // @@protoc_insertion_point(field_set:Cliente_Productor.estadoMSJ.recibido)
}
inline bool estadoMSJ::_internal_recibido() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.recibido_;
}
inline void estadoMSJ::_internal_set_recibido(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.recibido_ = value;
}

// -------------------------------------------------------------------

// Vacio

// -------------------------------------------------------------------

// solicitudMSJ

// int32 tema = 1;
inline void solicitudMSJ::clear_tema() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tema_ = 0;
}
inline ::int32_t solicitudMSJ::tema() const {
  // @@protoc_insertion_point(field_get:Cliente_Productor.solicitudMSJ.tema)
  return _internal_tema();
}
inline void solicitudMSJ::set_tema(::int32_t value) {
  _internal_set_tema(value);
  // @@protoc_insertion_point(field_set:Cliente_Productor.solicitudMSJ.tema)
}
inline ::int32_t solicitudMSJ::_internal_tema() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.tema_;
}
inline void solicitudMSJ::_internal_set_tema(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.tema_ = value;
}

// int32 idMensaje = 2;
inline void solicitudMSJ::clear_idmensaje() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.idmensaje_ = 0;
}
inline ::int32_t solicitudMSJ::idmensaje() const {
  // @@protoc_insertion_point(field_get:Cliente_Productor.solicitudMSJ.idMensaje)
  return _internal_idmensaje();
}
inline void solicitudMSJ::set_idmensaje(::int32_t value) {
  _internal_set_idmensaje(value);
  // @@protoc_insertion_point(field_set:Cliente_Productor.solicitudMSJ.idMensaje)
}
inline ::int32_t solicitudMSJ::_internal_idmensaje() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.idmensaje_;
}
inline void solicitudMSJ::_internal_set_idmensaje(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.idmensaje_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Cliente_Productor


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Cliente_5fProto_2eproto_2epb_2eh
