// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cliente_Proto.proto
// Protobuf C++ Version: 5.26.1

#include "Cliente_Proto.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Cliente_Productor {

inline constexpr solicitudMSJ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : tema_{0},
        idmensaje_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR solicitudMSJ::solicitudMSJ(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct solicitudMSJDefaultTypeInternal {
  PROTOBUF_CONSTEXPR solicitudMSJDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~solicitudMSJDefaultTypeInternal() {}
  union {
    solicitudMSJ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 solicitudMSJDefaultTypeInternal _solicitudMSJ_default_instance_;

inline constexpr estadoMSJ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : recibido_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR estadoMSJ::estadoMSJ(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct estadoMSJDefaultTypeInternal {
  PROTOBUF_CONSTEXPR estadoMSJDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~estadoMSJDefaultTypeInternal() {}
  union {
    estadoMSJ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 estadoMSJDefaultTypeInternal _estadoMSJ_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR Vacio::Vacio(::_pbi::ConstantInitialized) {}
struct VacioDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VacioDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VacioDefaultTypeInternal() {}
  union {
    Vacio _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VacioDefaultTypeInternal _Vacio_default_instance_;

inline constexpr Mensaje::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : contenido_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        tema_{0},
        idmensaje_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Mensaje::Mensaje(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MensajeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MensajeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MensajeDefaultTypeInternal() {}
  union {
    Mensaje _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MensajeDefaultTypeInternal _Mensaje_default_instance_;
}  // namespace Cliente_Productor
static ::_pb::Metadata file_level_metadata_Cliente_5fProto_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Cliente_5fProto_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Cliente_5fProto_2eproto = nullptr;
const ::uint32_t
    TableStruct_Cliente_5fProto_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::Mensaje, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::Mensaje, _impl_.tema_),
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::Mensaje, _impl_.idmensaje_),
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::Mensaje, _impl_.contenido_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::estadoMSJ, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::estadoMSJ, _impl_.recibido_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::Vacio, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::solicitudMSJ, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::solicitudMSJ, _impl_.tema_),
        PROTOBUF_FIELD_OFFSET(::Cliente_Productor::solicitudMSJ, _impl_.idmensaje_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Cliente_Productor::Mensaje)},
        {11, -1, -1, sizeof(::Cliente_Productor::estadoMSJ)},
        {20, -1, -1, sizeof(::Cliente_Productor::Vacio)},
        {28, -1, -1, sizeof(::Cliente_Productor::solicitudMSJ)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Cliente_Productor::_Mensaje_default_instance_._instance,
    &::Cliente_Productor::_estadoMSJ_default_instance_._instance,
    &::Cliente_Productor::_Vacio_default_instance_._instance,
    &::Cliente_Productor::_solicitudMSJ_default_instance_._instance,
};
const char descriptor_table_protodef_Cliente_5fProto_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023Cliente_Proto.proto\022\021Cliente_Productor"
    "\"=\n\007Mensaje\022\014\n\004tema\030\001 \001(\005\022\021\n\tidMensaje\030\002"
    " \001(\005\022\021\n\tcontenido\030\003 \001(\t\"\035\n\testadoMSJ\022\020\n\010"
    "recibido\030\001 \001(\010\"\007\n\005Vacio\"/\n\014solicitudMSJ\022"
    "\014\n\004tema\030\001 \001(\005\022\021\n\tidMensaje\030\002 \001(\0052\201\002\n\020Cli"
    "enteServicios\022K\n\renviarMensaje\022\032.Cliente"
    "_Productor.Mensaje\032\034.Cliente_Productor.e"
    "stadoMSJ\"\000\022M\n\017publicarMensaje\022\032.Cliente_"
    "Productor.Mensaje\032\034.Cliente_Productor.es"
    "tadoMSJ\"\000\022Q\n\020recibirMSJServer\022\037.Cliente_"
    "Productor.solicitudMSJ\032\032.Cliente_Product"
    "or.Mensaje\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_Cliente_5fProto_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Cliente_5fProto_2eproto = {
    false,
    false,
    460,
    descriptor_table_protodef_Cliente_5fProto_2eproto,
    "Cliente_Proto.proto",
    &descriptor_table_Cliente_5fProto_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_Cliente_5fProto_2eproto::offsets,
    file_level_metadata_Cliente_5fProto_2eproto,
    file_level_enum_descriptors_Cliente_5fProto_2eproto,
    file_level_service_descriptors_Cliente_5fProto_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Cliente_5fProto_2eproto_getter() {
  return &descriptor_table_Cliente_5fProto_2eproto;
}
namespace Cliente_Productor {
// ===================================================================

class Mensaje::_Internal {
 public:
};

Mensaje::Mensaje(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Cliente_Productor.Mensaje)
}
inline PROTOBUF_NDEBUG_INLINE Mensaje::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : contenido_(arena, from.contenido_),
        _cached_size_{0} {}

Mensaje::Mensaje(
    ::google::protobuf::Arena* arena,
    const Mensaje& from)
    : ::google::protobuf::Message(arena) {
  Mensaje* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, tema_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, tema_),
           offsetof(Impl_, idmensaje_) -
               offsetof(Impl_, tema_) +
               sizeof(Impl_::idmensaje_));

  // @@protoc_insertion_point(copy_constructor:Cliente_Productor.Mensaje)
}
inline PROTOBUF_NDEBUG_INLINE Mensaje::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : contenido_(arena),
        _cached_size_{0} {}

inline void Mensaje::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, tema_),
           0,
           offsetof(Impl_, idmensaje_) -
               offsetof(Impl_, tema_) +
               sizeof(Impl_::idmensaje_));
}
Mensaje::~Mensaje() {
  // @@protoc_insertion_point(destructor:Cliente_Productor.Mensaje)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Mensaje::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.contenido_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Mensaje::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Mensaje, _impl_._cached_size_),
              false,
          },
          &Mensaje::MergeImpl,
          &Mensaje::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Mensaje::Clear() {
// @@protoc_insertion_point(message_clear_start:Cliente_Productor.Mensaje)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.contenido_.ClearToEmpty();
  ::memset(&_impl_.tema_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.idmensaje_) -
      reinterpret_cast<char*>(&_impl_.tema_)) + sizeof(_impl_.idmensaje_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Mensaje::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 43, 2> Mensaje::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Mensaje_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Cliente_Productor::Mensaje>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 tema = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Mensaje, _impl_.tema_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(Mensaje, _impl_.tema_)}},
    // int32 idMensaje = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Mensaje, _impl_.idmensaje_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Mensaje, _impl_.idmensaje_)}},
    // string contenido = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Mensaje, _impl_.contenido_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 tema = 1;
    {PROTOBUF_FIELD_OFFSET(Mensaje, _impl_.tema_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 idMensaje = 2;
    {PROTOBUF_FIELD_OFFSET(Mensaje, _impl_.idmensaje_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string contenido = 3;
    {PROTOBUF_FIELD_OFFSET(Mensaje, _impl_.contenido_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\0\11\0\0\0\0"
    "Cliente_Productor.Mensaje"
    "contenido"
  }},
};

::uint8_t* Mensaje::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Cliente_Productor.Mensaje)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 tema = 1;
  if (this->_internal_tema() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_tema(), target);
  }

  // int32 idMensaje = 2;
  if (this->_internal_idmensaje() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_idmensaje(), target);
  }

  // string contenido = 3;
  if (!this->_internal_contenido().empty()) {
    const std::string& _s = this->_internal_contenido();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Cliente_Productor.Mensaje.contenido");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Cliente_Productor.Mensaje)
  return target;
}

::size_t Mensaje::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Cliente_Productor.Mensaje)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string contenido = 3;
  if (!this->_internal_contenido().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_contenido());
  }

  // int32 tema = 1;
  if (this->_internal_tema() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_tema());
  }

  // int32 idMensaje = 2;
  if (this->_internal_idmensaje() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_idmensaje());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Mensaje::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Mensaje*>(&to_msg);
  auto& from = static_cast<const Mensaje&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Cliente_Productor.Mensaje)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_contenido().empty()) {
    _this->_internal_set_contenido(from._internal_contenido());
  }
  if (from._internal_tema() != 0) {
    _this->_impl_.tema_ = from._impl_.tema_;
  }
  if (from._internal_idmensaje() != 0) {
    _this->_impl_.idmensaje_ = from._impl_.idmensaje_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Mensaje::CopyFrom(const Mensaje& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Cliente_Productor.Mensaje)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Mensaje::IsInitialized() const {
  return true;
}

void Mensaje::InternalSwap(Mensaje* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.contenido_, &other->_impl_.contenido_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Mensaje, _impl_.idmensaje_)
      + sizeof(Mensaje::_impl_.idmensaje_)
      - PROTOBUF_FIELD_OFFSET(Mensaje, _impl_.tema_)>(
          reinterpret_cast<char*>(&_impl_.tema_),
          reinterpret_cast<char*>(&other->_impl_.tema_));
}

::google::protobuf::Metadata Mensaje::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_Cliente_5fProto_2eproto_getter,
                                   &descriptor_table_Cliente_5fProto_2eproto_once,
                                   file_level_metadata_Cliente_5fProto_2eproto[0]);
}
// ===================================================================

class estadoMSJ::_Internal {
 public:
};

estadoMSJ::estadoMSJ(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Cliente_Productor.estadoMSJ)
}
estadoMSJ::estadoMSJ(
    ::google::protobuf::Arena* arena, const estadoMSJ& from)
    : estadoMSJ(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE estadoMSJ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void estadoMSJ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.recibido_ = {};
}
estadoMSJ::~estadoMSJ() {
  // @@protoc_insertion_point(destructor:Cliente_Productor.estadoMSJ)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void estadoMSJ::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
estadoMSJ::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(estadoMSJ, _impl_._cached_size_),
              false,
          },
          &estadoMSJ::MergeImpl,
          &estadoMSJ::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void estadoMSJ::Clear() {
// @@protoc_insertion_point(message_clear_start:Cliente_Productor.estadoMSJ)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.recibido_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* estadoMSJ::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> estadoMSJ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_estadoMSJ_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Cliente_Productor::estadoMSJ>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool recibido = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(estadoMSJ, _impl_.recibido_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(estadoMSJ, _impl_.recibido_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool recibido = 1;
    {PROTOBUF_FIELD_OFFSET(estadoMSJ, _impl_.recibido_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* estadoMSJ::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Cliente_Productor.estadoMSJ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool recibido = 1;
  if (this->_internal_recibido() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_recibido(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Cliente_Productor.estadoMSJ)
  return target;
}

::size_t estadoMSJ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Cliente_Productor.estadoMSJ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool recibido = 1;
  if (this->_internal_recibido() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void estadoMSJ::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<estadoMSJ*>(&to_msg);
  auto& from = static_cast<const estadoMSJ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Cliente_Productor.estadoMSJ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_recibido() != 0) {
    _this->_impl_.recibido_ = from._impl_.recibido_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void estadoMSJ::CopyFrom(const estadoMSJ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Cliente_Productor.estadoMSJ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool estadoMSJ::IsInitialized() const {
  return true;
}

void estadoMSJ::InternalSwap(estadoMSJ* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.recibido_, other->_impl_.recibido_);
}

::google::protobuf::Metadata estadoMSJ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_Cliente_5fProto_2eproto_getter,
                                   &descriptor_table_Cliente_5fProto_2eproto_once,
                                   file_level_metadata_Cliente_5fProto_2eproto[1]);
}
// ===================================================================

class Vacio::_Internal {
 public:
};

Vacio::Vacio(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:Cliente_Productor.Vacio)
}
Vacio::Vacio(
    ::google::protobuf::Arena* arena,
    const Vacio& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  Vacio* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Cliente_Productor.Vacio)
}









::google::protobuf::Metadata Vacio::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_Cliente_5fProto_2eproto_getter,
                                   &descriptor_table_Cliente_5fProto_2eproto_once,
                                   file_level_metadata_Cliente_5fProto_2eproto[2]);
}
// ===================================================================

class solicitudMSJ::_Internal {
 public:
};

solicitudMSJ::solicitudMSJ(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Cliente_Productor.solicitudMSJ)
}
solicitudMSJ::solicitudMSJ(
    ::google::protobuf::Arena* arena, const solicitudMSJ& from)
    : solicitudMSJ(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE solicitudMSJ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void solicitudMSJ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, tema_),
           0,
           offsetof(Impl_, idmensaje_) -
               offsetof(Impl_, tema_) +
               sizeof(Impl_::idmensaje_));
}
solicitudMSJ::~solicitudMSJ() {
  // @@protoc_insertion_point(destructor:Cliente_Productor.solicitudMSJ)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void solicitudMSJ::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
solicitudMSJ::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(solicitudMSJ, _impl_._cached_size_),
              false,
          },
          &solicitudMSJ::MergeImpl,
          &solicitudMSJ::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void solicitudMSJ::Clear() {
// @@protoc_insertion_point(message_clear_start:Cliente_Productor.solicitudMSJ)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.tema_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.idmensaje_) -
      reinterpret_cast<char*>(&_impl_.tema_)) + sizeof(_impl_.idmensaje_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* solicitudMSJ::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> solicitudMSJ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_solicitudMSJ_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Cliente_Productor::solicitudMSJ>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 idMensaje = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(solicitudMSJ, _impl_.idmensaje_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(solicitudMSJ, _impl_.idmensaje_)}},
    // int32 tema = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(solicitudMSJ, _impl_.tema_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(solicitudMSJ, _impl_.tema_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 tema = 1;
    {PROTOBUF_FIELD_OFFSET(solicitudMSJ, _impl_.tema_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 idMensaje = 2;
    {PROTOBUF_FIELD_OFFSET(solicitudMSJ, _impl_.idmensaje_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* solicitudMSJ::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Cliente_Productor.solicitudMSJ)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 tema = 1;
  if (this->_internal_tema() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_tema(), target);
  }

  // int32 idMensaje = 2;
  if (this->_internal_idmensaje() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_idmensaje(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Cliente_Productor.solicitudMSJ)
  return target;
}

::size_t solicitudMSJ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Cliente_Productor.solicitudMSJ)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 tema = 1;
  if (this->_internal_tema() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_tema());
  }

  // int32 idMensaje = 2;
  if (this->_internal_idmensaje() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_idmensaje());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void solicitudMSJ::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<solicitudMSJ*>(&to_msg);
  auto& from = static_cast<const solicitudMSJ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Cliente_Productor.solicitudMSJ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_tema() != 0) {
    _this->_impl_.tema_ = from._impl_.tema_;
  }
  if (from._internal_idmensaje() != 0) {
    _this->_impl_.idmensaje_ = from._impl_.idmensaje_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void solicitudMSJ::CopyFrom(const solicitudMSJ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Cliente_Productor.solicitudMSJ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool solicitudMSJ::IsInitialized() const {
  return true;
}

void solicitudMSJ::InternalSwap(solicitudMSJ* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(solicitudMSJ, _impl_.idmensaje_)
      + sizeof(solicitudMSJ::_impl_.idmensaje_)
      - PROTOBUF_FIELD_OFFSET(solicitudMSJ, _impl_.tema_)>(
          reinterpret_cast<char*>(&_impl_.tema_),
          reinterpret_cast<char*>(&other->_impl_.tema_));
}

::google::protobuf::Metadata solicitudMSJ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_Cliente_5fProto_2eproto_getter,
                                   &descriptor_table_Cliente_5fProto_2eproto_once,
                                   file_level_metadata_Cliente_5fProto_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Cliente_Productor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_Cliente_5fProto_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
